### ISSUE TITLE
Clicking anchor tags no longer filters results in some themes

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/AZ-Filters#46]
This affects Divi and also Kadence.

[This affects Try.](https://site.try.gravitykit.com/business-directory-map/#gv-widget-az_filter-1)

The links don't work anymore:

https://user-images.githubusercontent.com/1222472/188958069-b68508d8-990f-40f9-ad6b-89de8c812f2c.mp4

Tested with AZ 1.3.1

**Comment by rafaehlers** [comment]
To download Divi: https://www.elegantthemes.com/members-area/
Login: https://docs.gravitykit.com/article/343-logins

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/2001812975/43326

**Comment by zackkatz** [comment]
This is indeed their issue—the selector they use is 

```
a[href*="#"]:not([href="#"])
```

It should be updated to make sure that the link _starts_ with a hash:

```
a[href^="#"]:not([href="#"])
```
